name = "ROTEX"
version = "0.1.5"
license = "MIT"
author = "Josh Forer"
maintainer = "jbf2177@columbia.edu"
copyright = "2025 Josh Forer"

[library]
source-dir = "src"

[build]
link = ["lapack"]
[preprocess]
[preprocess.cpp]
suffixes = [".f"]
macros = ["USE_FORBEAR", "USE_CDMSREADER", "USE_OPENMP"]

[dependencies]
forbear         = { git = "https://github.com/szaghi/forbear",                branch = "master" }
CDMSreader      = { git = "https://github.com/banana-bred/CDMSreader",        branch = "main" }
wignerd         = { git = "https://github.com/banana-bred/wignerd",           branch = "main" }
bspline-fortran = { git = "https://github.com/jacobwilliams/bspline-fortran", branch = "master" }
openmp = "*"

[[executable]]
main="rotex.f"
source-dir="main"
name="rotex"

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
